# Generated by Django 2.2.6 on 2019-12-30 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Title')),
                ('image', models.ImageField(upload_to='', verbose_name='Background image')),
                ('text_button', models.CharField(max_length=50, verbose_name='Text button')),
                ('description', models.CharField(max_length=200, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Home model',
                'db_table': 'home_model',
            },
        ),
    ]
