version: '3.7'

services:
  postgres:
    image: postgres:10.3-alpine
    container_name: parser_db
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

  web:
    container_name: parser_web
    working_dir: /var/www/html
    command: ls -la
    volumes:
      - "${WORK_FOLDER}:/var/www/html"
    build:
      context: web

