version: '3.3'

services:
  postgres:
    image: postgres:10.3-alpine
    container_name: parser_db
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"

  web:
    build:
      context: web
    container_name: parser_web
    command: python manage.py runserver
