version: '3.7'

services:
  postgres:
    image: postgres:11.2
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - 5432:5432

  web:
    image: python:3.7
    working_dir: /var/django-parser-demo/src/web
    entrypoint: ./entrypoint.sh
    volumes:
      - ${WORK_FOLDER}:/var/django-parser-demo
    ports:
      - 8000:8000
    depends_on:
      - postgres
