version: '3.7'

services:
  postgres:
    image: postgres:10.3-alpine
    container_name: parser_db
    environment:
      POSTGRES_DB: "${POSTGRES_DB}"
      POSTGRES_USER: "${POSTGRES_USER}"
      POSTGRES_PASSWORD: "${POSTGRES_PASSWORD}"
    ports:
      - 5432:5432

  web:
    image: python:3.7
    container_name: parser_web
    working_dir: /var/django-parser-demo/src/web
    command: bash -c "pip install -r requirements.txt && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    volumes:
      - "${WORK_FOLDER}:/var/django-parser-demo"
    ports:
      - 8000:8000
    depends_on:
      - parser_db
