version: '3.7'

services:
  postgres:
    image: postgres:11.2
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - ../volumes/postgres/data:/var/lib/postgresql/data  #save database

  web:
    build:
      context: web
    working_dir: /var/django-parser-demo/src/web
    entrypoint:
      - ../../docker/web/wait-for-it.sh
      - ./entrypoint.sh
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ${WORK_FOLDER}:/var/django-parser-demo
      - ../volumes/logs:/var/django-parser-demo/logs/web # save logs application
    ports:
      - 8000:8000
    depends_on:
      - postgres
